import json
import os
import pathlib
from os.path import join

import pandas as pd
from sklearn import metrics
from sklearn.exceptions import ConvergenceWarning
from tqdm import tqdm
import numpy as np
import quapy as qp
import warnings

from commons import N_RUNS, get_full_path

warnings.filterwarnings("ignore", category=UserWarning, module='sklearn')
warnings.filterwarnings("ignore", category=ConvergenceWarning, module='sklearn')

# implementations from: https://github.com/jindongwang/transferlearning/blob/master/code/distance/mmd_numpy_sklearn.py

def mmd_linear(X, Y):
    """MMD using linear kernel (i.e., k(x,y) = <x,y>)
    Note that this is not the original linear MMD, only the reformulated and faster version.
    The original version is:
        def mmd_linear(X, Y):
            XX = np.dot(X, X.T)
            YY = np.dot(Y, Y.T)
            XY = np.dot(X, Y.T)
            return XX.mean() + YY.mean() - 2 * XY.mean()

    Arguments:
        X {[n_sample1, dim]} -- [X matrix]
        Y {[n_sample2, dim]} -- [Y matrix]

    Returns:
        [scalar] -- [MMD value]
    """
    delta = X.mean(0) - Y.mean(0)
    return delta.dot(delta.T)


def mmd_rbf(X, Y, gamma=1.0):
    """MMD using rbf (gaussian) kernel (i.e., k(x,y) = exp(-gamma * ||x-y||^2 / 2))

    Arguments:
        X {[n_sample1, dim]} -- [X matrix]
        Y {[n_sample2, dim]} -- [Y matrix]

    Keyword Arguments:
        gamma {float} -- [kernel parameter] (default: {1.0})

    Returns:
        [scalar] -- [MMD value]
    """
    XX = metrics.pairwise.rbf_kernel(X, X, gamma)
    YY = metrics.pairwise.rbf_kernel(Y, Y, gamma)
    XY = metrics.pairwise.rbf_kernel(X, Y, gamma)
    return XX.mean() + YY.mean() - 2 * XY.mean()


def mmd_rbf_matrix(X, Y, gamma=1.0):
    Z = np.vstack([X,Y])
    ZZ = metrics.pairwise.rbf_kernel(Z, gamma=gamma)
    return ZZ


def mmd_rbf_blocks(X, Y, blocks_idx, gammas=1.):
    if isinstance(gammas, float):
        gammas = [gammas]*len(blocks_idx)

    mmd = 0
    for block_idx, gamma in zip(blocks_idx, gammas):
        mmd+=mmd_rbf(X[:,block_idx], Y[:,block_idx], gamma)

    return mmd


def mmd_rbf_blocks_matrix(X, Y, blocks_idx, gammas=1.):
    if isinstance(gammas, float):
        gammas = [gammas]*len(blocks_idx)

    M = None
    for block_idx, gamma in zip(blocks_idx, gammas):
        M_block = mmd_rbf_matrix(X[:,block_idx], Y[:,block_idx], gamma)
        if M is None:
            M = M_block
        else:
            M += M_block

    return M

def mmd_pairwise_rbf_blocks(Xs, blocks_idx, gammas=1., **kwargs):
    n = len(Xs)
    mmd_matrix = np.zeros(shape=(n, n))
    for i in range(n-1):
        for j in range(i+1, n):
            mmd = mmd_rbf_blocks(Xs[i], Xs[j], blocks_idx, gammas)
            mmd_matrix[i, j] = mmd
            mmd_matrix[j, i] = mmd
    return mmd_matrix


def mmd_rbf_blocks_pval(X, Y, blocks_idx, gammas=1., trials=1000):
    M = mmd_rbf_blocks_matrix(X, Y, blocks_idx, gammas)

    nX, nY = X.shape[0], Y.shape[0]
    nZ = nX + nY

    def MMD_from_matrix(M, nX, nY):
        XX = M[:nX,:nX]
        YY = M[nX:,nX:]
        XY = M[:nX,nX:]
        return XX.mean()+YY.mean()-2*XY.mean()

    mmd = MMD_from_matrix(M, nX, nY)

    mmds_null = []
    for _ in tqdm(range(trials), total=trials):
        idx = np.random.permutation(nZ)
        M = M[np.ix_(idx, idx)]
        mmds_null.append(MMD_from_matrix(M, nX, nY))

    mmds_null = np.asarray(mmds_null)
    p_value = np.mean(mmds_null >= mmd)

    return mmd, p_value


def mmd_pairwise_rbf_blocks_pval(Xs, blocks_idx, gammas=1.):
    n = len(Xs)
    mmd_matrix = np.zeros(shape=(n, n))
    mmd_pvals = np.zeros(shape=(n, n))

    def job(args):
        Xi, Xj, blocks_idx, gammas = args
        return mmd_rbf_blocks_pval(Xi, Xj, blocks_idx, gammas)

    mmds_pvals = qp.util.parallel(job, [(Xs[i], Xs[j], blocks_idx, gammas) for i in range(n-1) for j in range(i+1,n)], n_jobs=-1, asarray=False)
    it=0
    for i in range(n-1):
        for j in range(i+1, n):
            mmd, pval = mmds_pvals[it]
            it+=1
            # mmd, pval = mmd_rbf_blocks_pval(Xs[i], Xs[j], blocks_idx, gammas)
            mmd_matrix[i, j] = mmd
            mmd_matrix[j, i] = mmd
            mmd_pvals[i, j] = pval
            mmd_pvals[j, i] = pval
    return mmd_matrix, mmd_pvals


def AUC_from_result_df(result_df):
    aucs = []
    for run in range(N_RUNS):
        result_run = result_df[result_df['run']==run]
        grouped = result_run.groupby('tr_size', sort=True)['nmd'].mean().reset_index()
        tr_size = grouped['tr_size'].tolist()
        nmd_means = grouped['nmd'].tolist()
        auc = np.trapz(y=nmd_means, x=tr_size)
        aucs.append(auc)
    return aucs


def _load_exploration_report(method, result_dir, config_path, dataset):
    # auxiliary function: loads an "exploratory report" (the report generated by the Greedy search) and
    # enriches it with additional information (std, relative improvement wrt the "all features" reference, etc.)
    result_all_features = load_precomputed_result(
        '../results/random_split_features', dataset, method=method, feature_block='all'
    )
    result_all_features_mean = np.mean(result_all_features)
    result_all_features_std = np.std(result_all_features)

    result_path = join(result_dir, 'exploration', config_path, f'{method}_exploration.json')
    os.makedirs(pathlib.Path(result_path).parent, exist_ok=True)
    with open(result_path, "r", encoding="utf-8") as f:
        exploration_data = json.load(f)
        exploration_data['reference_all_score'] = result_all_features_mean
        exploration_data['reference_all_score_std'] = result_all_features_std
        exploration_data['rel_all_err_reduction'] = 100 * (result_all_features_mean - exploration_data['final_score']) / result_all_features_mean

        # compute std across runs of the optimized version
        best_path = exploration_data['best_conf_path']
        df = pd.read_csv(best_path, index_col=0)
        aucs = AUC_from_result_df(df)
        exploration_data['final_score_std'] = np.std(aucs)

        return exploration_data


def load_precomputed_result(result_dir, dataset_name, method, feature_block='all'):
    # returns the AUC for the best feature-block setup (or "ALL" if not indicated).
    # This is the reference value we want to beat
    result_dir = get_full_path(result_dir, dataset_name)
    result_file = join(result_dir, f'{method}__{feature_block}.csv')
    assert os.path.exists(result_file), f'result file {result_file} does not exist'
    df = pd.read_csv(result_file, index_col=0)
    auc = AUC_from_result_df(df)
    return auc
